<template>
    <div class="DSM-Algorithm">
        <el-radio-group type="simple" v-model="sentivityType">
            <el-radio-button
                v-for="(
                    item, index
                ) in enumerationJSON.intelliDrive_DSM_newSensitivity"
                :key="index"
                :label="item.value"
            >
                {{ item.label }}灵敏度
            </el-radio-button>
        </el-radio-group>
        <el-form
            :label-width="`175px`"
            :model="newForm"
            :inline="true"
            ref="form"
        >
            <div class="form-title">
                <span>功能</span>
                <el-button
                    v-if="!isTemplate"
                    size="small"
                    type="primary"
                    icon="el-icon-refresh-left"
                    @click="resetValue"
                    >恢复默认值</el-button
                >
            </div>
            <div class="collapse-box">
                <el-collapse
                    v-model="activeCollapse"
                    v-if="newForm[`param6004_0_${sentivityType}`]"
                >
                    <el-collapse-item
                        title="疲劳驾驶-闭眼疲劳"
                        name="closedEyeFatigue"
                        v-if="
                            customizeAlgorithm.closedEyeFatigue &&
                            newForm[`param6004_0_${sentivityType}`]
                                .closedEyeFatigue
                        "
                    >
                        <el-form-item
                            label="预警范围"
                            v-if="
                                customizeAlgorithm.closedEyeFatigue
                                    .preCloseRange
                            "
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .closedEyeFatigue.preCloseRange
                                "
                                :min="
                                    customizeAlgorithm.closedEyeFatigue
                                        .preCloseRange.rangeMin
                                "
                                :max="
                                    customizeAlgorithm.closedEyeFatigue
                                        .preCloseRange.rangeMax
                                "
                                data-unit="s"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].closedEyeFatigue.preCloseRange =
                                                Number(e.target.ariaValueMin);
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="闭眼百分比"
                            v-if="customizeAlgorithm.closedEyeFatigue.radio"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .closedEyeFatigue.radio
                                "
                                :min="
                                    customizeAlgorithm.closedEyeFatigue.radio
                                        .rangeMin
                                "
                                :max="
                                    customizeAlgorithm.closedEyeFatigue.radio
                                        .rangeMax
                                "
                                data-unit="%"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].closedEyeFatigue.radio = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="闭眼持续时间"
                            v-if="customizeAlgorithm.closedEyeFatigue.duration"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .closedEyeFatigue.duration
                                "
                                :min="
                                    customizeAlgorithm.closedEyeFatigue.duration
                                        .rangeMin
                                "
                                :max="
                                    customizeAlgorithm.closedEyeFatigue.duration
                                        .rangeMax
                                "
                                data-unit="s"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].closedEyeFatigue.duration =
                                                Number(e.target.ariaValueMin);
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="头部姿态"
                            v-if="
                                customizeAlgorithm.closedEyeFatigue.headPosture
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .closedEyeFatigue.headPosture
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="讲话过滤"
                            v-if="
                                customizeAlgorithm.closedEyeFatigue.speakFilter
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .closedEyeFatigue.speakFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="低头过滤"
                            v-if="
                                customizeAlgorithm.closedEyeFatigue
                                    .lowHeadFilter
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .closedEyeFatigue.lowHeadFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="眯眼过滤"
                            v-if="
                                customizeAlgorithm.closedEyeFatigue.squintFilter
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .closedEyeFatigue.squintFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="非疲劳动作过滤"
                            v-if="
                                customizeAlgorithm.closedEyeFatigue
                                    .nonFatigueActionFilter
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .closedEyeFatigue.nonFatigueActionFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="人脸不能过小"
                            v-if="customizeAlgorithm.closedEyeFatigue.smallFace"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .closedEyeFatigue.smallFace
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="亮度异常"
                            v-if="
                                customizeAlgorithm.closedEyeFatigue
                                    .abnormalBrightness
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .closedEyeFatigue.abnormalBrightness
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="眼部质量要求"
                            v-if="
                                customizeAlgorithm.closedEyeFatigue.eyeQuality
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .closedEyeFatigue.eyeQuality
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="历史疲劳信息"
                            v-if="
                                customizeAlgorithm.closedEyeFatigue
                                    .historyFatigue
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .closedEyeFatigue.historyFatigue
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="人脸角度大于分心角度"
                            v-if="
                                customizeAlgorithm.closedEyeFatigue
                                    .faceAngleFilter
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .closedEyeFatigue.faceAngleFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="人脸靠近画面水平边缘"
                            v-if="
                                customizeAlgorithm.closedEyeFatigue
                                    .horizontalEdgeFaceFilter
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .closedEyeFatigue
                                        .horizontalEdgeFaceFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="人脸靠近画面垂直边缘"
                            v-if="
                                customizeAlgorithm.closedEyeFatigue
                                    .verticalEdgeFaceFilter
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .closedEyeFatigue.verticalEdgeFaceFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                    </el-collapse-item>
                    <el-collapse-item
                        title="疲劳驾驶-打哈欠疲劳"
                        name="yawn"
                        v-if="
                            customizeAlgorithm.yawn &&
                            newForm[`param6004_0_${sentivityType}`].yawn
                        "
                    >
                        <el-form-item
                            label="持续时长"
                            v-if="customizeAlgorithm.yawn.duration"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`].yawn
                                        .duration
                                "
                                :min="customizeAlgorithm.yawn.duration.rangeMin"
                                :max="customizeAlgorithm.yawn.duration.rangeMax"
                                data-unit="s"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].yawn.duration = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="讲话过滤"
                            v-if="customizeAlgorithm.yawn.speakFilter"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`].yawn
                                        .speakFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="疲态过滤"
                            v-if="customizeAlgorithm.yawn.fatigueFilter"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`].yawn
                                        .fatigueFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="无关动作过滤"
                            v-if="customizeAlgorithm.yawn.unrelatedActionFilter"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`].yawn
                                        .unrelatedActionFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="持续张嘴过滤"
                            v-if="customizeAlgorithm.yawn.openMouthFilter"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`].yawn
                                        .openMouthFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                    </el-collapse-item>
                    <el-collapse-item
                        title="接打电话"
                        name="phoneCall"
                        v-if="
                            customizeAlgorithm.phoneCall &&
                            newForm[`param6004_0_${sentivityType}`].phoneCall
                        "
                    >
                        <el-form-item
                            label="持续时长"
                            v-if="customizeAlgorithm.phoneCall.duration"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .phoneCall.duration
                                "
                                :min="
                                    customizeAlgorithm.phoneCall.duration
                                        .rangeMin
                                "
                                :max="
                                    customizeAlgorithm.phoneCall.duration
                                        .rangeMax
                                "
                                data-unit="s"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].phoneCall.duration = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="百分比"
                            v-if="customizeAlgorithm.phoneCall.radio"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .phoneCall.radio
                                "
                                :min="
                                    customizeAlgorithm.phoneCall.radio.rangeMin
                                "
                                :max="
                                    customizeAlgorithm.phoneCall.radio.rangeMax
                                "
                                data-unit="%"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].phoneCall.radio = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="电话位置合理性过滤"
                            v-if="
                                customizeAlgorithm.phoneCall.phoneLocationFilter
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .phoneCall.phoneLocationFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="对讲机过滤"
                            v-if="customizeAlgorithm.phoneCall.interPhoneFilter"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .phoneCall.interPhoneFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="需要唇动"
                            v-if="customizeAlgorithm.phoneCall.needLipMovement"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .phoneCall.needLipMovement
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="不能伴随吃东西或喝水动作"
                            v-if="customizeAlgorithm.phoneCall.chewAndDrink"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .phoneCall.chewAndDrink
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="需要背景建模"
                            v-if="customizeAlgorithm.phoneCall.backgroundModel"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .phoneCall.backgroundModel
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="检测到玩手机但是没有手"
                            v-if="customizeAlgorithm.phoneCall.callWithoutHand"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .phoneCall.callWithoutHand
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="疑似方向盘遮挡电话过滤"
                            v-if="customizeAlgorithm.phoneCall.wheelMaskFilter"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .phoneCall.wheelMaskFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                    </el-collapse-item>
                    <el-collapse-item
                        title="抽烟"
                        name="smoking"
                        v-if="
                            customizeAlgorithm.smoking &&
                            newForm[`param6004_0_${sentivityType}`].smoking
                        "
                    >
                        <el-form-item
                            label="持续时长"
                            v-if="customizeAlgorithm.smoking.duration"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .smoking.duration
                                "
                                :min="
                                    customizeAlgorithm.smoking.duration.rangeMin
                                "
                                :max="
                                    customizeAlgorithm.smoking.duration.rangeMax
                                "
                                data-unit="s"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].smoking.duration = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="百分比"
                            v-if="customizeAlgorithm.smoking.radio"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .smoking.radio
                                "
                                :min="customizeAlgorithm.smoking.radio.rangeMin"
                                :max="customizeAlgorithm.smoking.radio.rangeMax"
                                data-unit="%"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].smoking.radio = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="手持烟放嘴边动作"
                            v-if="customizeAlgorithm.smoking.handheldCigarette"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .smoking.handheldCigarette
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="烟与嘴有交集"
                            v-if="
                                customizeAlgorithm.smoking
                                    .smallAndmouthIntersect
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .smoking.smallAndmouthIntersect
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="不能伴随吃东西或喝水动作"
                            v-if="customizeAlgorithm.smoking.chewAndDrink"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .smoking.chewAndDrink
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="相同位置一直有抽烟报警"
                            v-if="customizeAlgorithm.smoking.samePosition"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .smoking.samePosition
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                    </el-collapse-item>
                    <el-collapse-item
                        title="分神驾驶"
                        name="distraction"
                        v-if="
                            customizeAlgorithm.distraction &&
                            newForm[`param6004_0_${sentivityType}`].distraction
                        "
                    >
                        <el-form-item
                            label="持续时长"
                            v-if="customizeAlgorithm.distraction.duration"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .distraction.duration
                                "
                                :min="
                                    customizeAlgorithm.distraction.duration
                                        .rangeMin
                                "
                                :max="
                                    customizeAlgorithm.distraction.duration
                                        .rangeMax
                                "
                                data-unit="s"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].distraction.duration = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="转头参数左"
                            v-if="customizeAlgorithm.distraction.turnParam1"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .distraction.turnParam1
                                "
                                :min="
                                    customizeAlgorithm.distraction.turnParam1
                                        .rangeMin
                                "
                                :max="
                                    customizeAlgorithm.distraction.turnParam1
                                        .rangeMax
                                "
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].distraction.turnParam1 = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="转头参数右"
                            v-if="customizeAlgorithm.distraction.turnParam2"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .distraction.turnParam2
                                "
                                :min="
                                    customizeAlgorithm.distraction.turnParam2
                                        .rangeMin
                                "
                                :max="
                                    customizeAlgorithm.distraction.turnParam2
                                        .rangeMax
                                "
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].distraction.turnParam2 = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="转头参数下"
                            v-if="customizeAlgorithm.distraction.turnParam3"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .distraction.turnParam3
                                "
                                :min="
                                    customizeAlgorithm.distraction.turnParam3
                                        .rangeMin
                                "
                                :max="
                                    customizeAlgorithm.distraction.turnParam3
                                        .rangeMax
                                "
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].distraction.turnParam3 = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="转头参数上"
                            v-if="customizeAlgorithm.distraction.turnParam4"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .distraction.turnParam4
                                "
                                :min="
                                    customizeAlgorithm.distraction.turnParam4
                                        .rangeMin
                                "
                                :max="
                                    customizeAlgorithm.distraction.turnParam4
                                        .rangeMax
                                "
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].distraction.turnParam4 = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="无关动作过滤"
                            v-if="
                                customizeAlgorithm.distraction
                                    .unrelatedActionFilter
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .distraction.unrelatedActionFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="基准不稳定或架设角度过大"
                            v-if="
                                customizeAlgorithm.distraction
                                    .benchmarkInstability
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .distraction.benchmarkInstability
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="启动阶段不报分心"
                            v-if="customizeAlgorithm.distraction.warningFilter"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .distraction.warningFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="手摸脸过滤"
                            v-if="
                                customizeAlgorithm.distraction.touchFaceFilter
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .distraction.touchFaceFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="吃东西、喝水时过滤"
                            v-if="customizeAlgorithm.distraction.drinkingFilter"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .distraction.drinkingFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="低置信度过滤"
                            v-if="
                                customizeAlgorithm.distraction.lowConfFaceFilter
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .distraction.lowConfFaceFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="靠近画面边缘时过滤"
                            v-if="customizeAlgorithm.distraction.edgeFaceFilter"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .distraction.edgeFaceFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="扭头检测"
                            v-if="
                                customizeAlgorithm.distraction.disHeadTwistDet
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .distraction.disHeadTwistDet
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                    </el-collapse-item>
                    <el-collapse-item
                        title="摄像头遮挡"
                        name="hide"
                        v-if="
                            customizeAlgorithm.hide &&
                            newForm[`param6004_0_${sentivityType}`].hide
                        "
                    >
                        <el-form-item
                            label="持续时长"
                            v-if="customizeAlgorithm.hide.duration"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`].hide
                                        .duration
                                "
                                :min="customizeAlgorithm.hide.duration.rangeMin"
                                :max="customizeAlgorithm.hide.duration.rangeMax"
                                data-unit="s"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].hide.duration = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="百分比"
                            v-if="customizeAlgorithm.hide.radio"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`].hide
                                        .radio
                                "
                                :min="customizeAlgorithm.hide.radio.rangeMin"
                                :max="customizeAlgorithm.hide.radio.rangeMax"
                                data-unit="%"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].hide.radio = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="简单遮挡"
                            v-if="customizeAlgorithm.hide.simpleHide"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`].hide
                                        .simpleHide
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="物件不检测"
                            v-if="customizeAlgorithm.hide.detectDisable"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`].hide
                                        .detectDisable
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="开机检测"
                            v-if="customizeAlgorithm.hide.bootDetect"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`].hide
                                        .bootDetect
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                    </el-collapse-item>
                    <el-collapse-item
                        title="未系安全带"
                        name="seatbelt"
                        v-if="
                            customizeAlgorithm.seatbelt &&
                            newForm[`param6004_0_${sentivityType}`].seatbelt
                        "
                    >
                        <el-form-item
                            label="持续时长"
                            v-if="customizeAlgorithm.seatbelt.duration"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .seatbelt.duration
                                "
                                :min="
                                    customizeAlgorithm.seatbelt.duration
                                        .rangeMin
                                "
                                :max="
                                    customizeAlgorithm.seatbelt.duration
                                        .rangeMax
                                "
                                data-unit="s"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].seatbelt.duration = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="百分比"
                            v-if="customizeAlgorithm.seatbelt.radio"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .seatbelt.radio
                                "
                                :min="
                                    customizeAlgorithm.seatbelt.radio.rangeMin
                                "
                                :max="
                                    customizeAlgorithm.seatbelt.radio.rangeMax
                                "
                                data-unit="%"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].seatbelt.radio = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="人脸位置"
                            v-if="customizeAlgorithm.seatbelt.facePosition"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .seatbelt.facePosition
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="人脸大小"
                            v-if="customizeAlgorithm.seatbelt.faceSize"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .seatbelt.faceSize
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="人脸角度"
                            v-if="customizeAlgorithm.seatbelt.faceAngle"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .seatbelt.faceAngle
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="人脸亮度"
                            v-if="customizeAlgorithm.seatbelt.faceBrightness"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .seatbelt.faceBrightness
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="肩膀"
                            v-if="customizeAlgorithm.seatbelt.shoulder"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .seatbelt.shoulder
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="不能检测到交集"
                            v-if="customizeAlgorithm.seatbelt.noInterSection"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .seatbelt.noInterSection
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="方向盘不遮挡"
                            v-if="customizeAlgorithm.seatbelt.noBlockSeatBelt"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .seatbelt.noBlockSeatBelt
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="累计报警过滤"
                            v-if="
                                customizeAlgorithm.seatbelt
                                    .accumulatedAlarmFliter
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .seatbelt.accumulatedAlarmFliter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="时间过滤"
                            v-if="customizeAlgorithm.seatbelt.timeFilter"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .seatbelt.timeFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                    </el-collapse-item>
                    <el-collapse-item
                        title="驾驶员身份识别异常"
                        name="driverAbnormal"
                        v-if="
                            customizeAlgorithm.driverAbnormal &&
                            newForm[`param6004_0_${sentivityType}`]
                                .driverAbnormal
                        "
                    >
                        <el-form-item
                            label="持续时长"
                            v-if="customizeAlgorithm.driverAbnormal.duration"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .driverAbnormal.duration
                                "
                                :min="
                                    customizeAlgorithm.driverAbnormal.duration
                                        .rangeMin
                                "
                                :max="
                                    customizeAlgorithm.driverAbnormal.duration
                                        .rangeMax
                                "
                                data-unit="s"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].driverAbnormal.duration = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="百分比"
                            v-if="customizeAlgorithm.driverAbnormal.radio"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .driverAbnormal.radio
                                "
                                :min="
                                    customizeAlgorithm.driverAbnormal.radio
                                        .rangeMin
                                "
                                :max="
                                    customizeAlgorithm.driverAbnormal.radio
                                        .rangeMax
                                "
                                data-unit="%"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].driverAbnormal.radio = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="头部不合理"
                            v-if="
                                customizeAlgorithm.driverAbnormal
                                    .headUnreasonable
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .driverAbnormal.headUnreasonable
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="头部消失"
                            v-if="
                                customizeAlgorithm.driverAbnormal.headDisppear
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .driverAbnormal.headDisppear
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="物件不检测"
                            v-if="
                                customizeAlgorithm.driverAbnormal.detectDisable
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .driverAbnormal.detectDisable
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                    </el-collapse-item>
                    <el-collapse-item
                        title="脱把"
                        name="takeOffHandle"
                        v-if="
                            customizeAlgorithm.takeOffHandle &&
                            newForm[`param6004_0_${sentivityType}`]
                                .takeOffHandle
                        "
                    >
                        <el-form-item
                            label="持续时长"
                            v-if="customizeAlgorithm.takeOffHandle.duration"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .takeOffHandle.duration
                                "
                                :min="
                                    customizeAlgorithm.takeOffHandle.duration
                                        .rangeMin
                                "
                                :max="
                                    customizeAlgorithm.takeOffHandle.duration
                                        .rangeMax
                                "
                                data-unit="s"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].takeOffHandle.duration = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="百分比"
                            v-if="customizeAlgorithm.takeOffHandle.radio"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .takeOffHandle.radio
                                "
                                :min="
                                    customizeAlgorithm.takeOffHandle.radio
                                        .rangeMin
                                "
                                :max="
                                    customizeAlgorithm.takeOffHandle.radio
                                        .rangeMax
                                "
                                data-unit="%"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].takeOffHandle.radio = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="位置异常"
                            v-if="
                                customizeAlgorithm.takeOffHandle
                                    .abnormalPosition
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .takeOffHandle.abnormalPosition
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="人脸位置异常"
                            v-if="
                                customizeAlgorithm.takeOffHandle
                                    .facePositionAbnormal
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .takeOffHandle.facePositionAbnormal
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="脱把过程"
                            v-if="
                                customizeAlgorithm.takeOffHandle
                                    .takeOffHandleAction
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .takeOffHandle.takeOffHandleAction
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="亮度"
                            v-if="customizeAlgorithm.takeOffHandle.brightness"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .takeOffHandle.brightness
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                    </el-collapse-item>
                    <el-collapse-item
                        title="玩手机"
                        name="playPhone"
                        v-if="
                            customizeAlgorithm.playPhone &&
                            newForm[`param6004_0_${sentivityType}`].playPhone
                        "
                    >
                        <el-form-item
                            label="持续时长"
                            v-if="customizeAlgorithm.playPhone.duration"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .playPhone.duration
                                "
                                :min="
                                    customizeAlgorithm.playPhone.duration
                                        .rangeMin
                                "
                                :max="
                                    customizeAlgorithm.playPhone.duration
                                        .rangeMax
                                "
                                data-unit="s"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].playPhone.duration = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="百分比"
                            v-if="customizeAlgorithm.playPhone.radio"
                        >
                            <el-input-number
                                :precision="0"
                                controls-position="right"
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .playPhone.radio
                                "
                                :min="
                                    customizeAlgorithm.playPhone.radio.rangeMin
                                "
                                :max="
                                    customizeAlgorithm.playPhone.radio.rangeMax
                                "
                                data-unit="%"
                                @blur="
                                    (e) => {
                                        if (e.target.value === '') {
                                            newForm[
                                                `param6004_0_${sentivityType}`
                                            ].playPhone.radio = Number(
                                                e.target.ariaValueMin
                                            );
                                        }
                                    }
                                "
                            ></el-input-number>
                        </el-form-item>
                        <el-form-item
                            label="人脸位置异常"
                            v-if="
                                customizeAlgorithm.playPhone
                                    .facePositionAbnormal
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .playPhone.facePositionAbnormal
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="手在方向盘内"
                            v-if="customizeAlgorithm.playPhone.handAndWheel"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .playPhone.handAndWheel
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="手不能在仪表盘内"
                            v-if="customizeAlgorithm.playPhone.phoneAndPenel"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .playPhone.phoneAndPenel
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="手和手机有交集"
                            v-if="customizeAlgorithm.playPhone.handAndPhone"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .playPhone.handAndPhone
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="背景过滤"
                            v-if="customizeAlgorithm.playPhone.backgroundFilter"
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .playPhone.backgroundFilter
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                    </el-collapse-item>
                    <el-collapse-item
                        title="架设异常"
                        name="abnormalInstallation"
                        v-if="
                            customizeAlgorithm.abnormalInstallation &&
                            newForm[`param6004_0_${sentivityType}`]
                                .abnormalInstallation
                        "
                    >
                        <el-form-item
                            label="稳定人脸时关闭架设异常"
                            v-if="
                                customizeAlgorithm.abnormalInstallation
                                    .abnPauseIfFaceStable
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .abnormalInstallation
                                        .abnPauseIfFaceStable
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                        <el-form-item
                            label="仅在行驶状态下检测"
                            v-if="
                                customizeAlgorithm.abnormalInstallation
                                    .abnPauseIfNotDriving
                            "
                        >
                            <el-switch
                                v-model="
                                    newForm[`param6004_0_${sentivityType}`]
                                        .abnormalInstallation
                                        .abnPauseIfNotDriving
                                "
                                :active-value="Number(1)"
                                :inactive-value="Number(0)"
                            ></el-switch>
                        </el-form-item>
                    </el-collapse-item>
                </el-collapse>
            </div>
        </el-form>
    </div>
</template>
<script>
import enumerationJSON from "../enumerationJSON/enumeration.json";
export default {
    name: "DSM-Algorithm",
    components: {},
    props: {
        newForm: {
            type: Object,
            default: () => {},
        },
        oldForm: {
            type: Object,
            default: () => {},
        },
        customizeAlgorithm: {
            type: Object,
            default: () => {},
        },
        chanNoActive: {
            type: String,
            default: "",
        },
        isTemplate: {
            type: Boolean,
            default: false,
        },
    },
    data() {
        return {
            enumerationJSON,
            sentivityType: 0,
            activeCollapse: "closedEyeFatigue",
            setForm: {},
        };
    },
    mounted() {},
    computed: {},
    watch: {
        newForm: {
            handler(val) {
                if (val) {
                    this.enumerationJSON.intelliDrive_DSM_newSensitivity.forEach(
                        (item) => {
                            if (
                                !this.setForm.hasOwnProperty(
                                    `${this.chanNoActive}>DSM灵敏度配置&param6004`
                                )
                            ) {
                                this.setForm[
                                    `${this.chanNoActive}>DSM灵敏度配置&param6004`
                                ] = {};
                            }
                            this.setForm[
                                `${this.chanNoActive}>DSM灵敏度配置&param6004`
                            ][`param6004_0_${item.value}`] =
                                JSON.stringify(
                                    val[`param6004_0_${item.value}`]
                                ) !=
                                JSON.stringify(
                                    this.oldForm[`param6004_0_${item.value}`]
                                )
                                    ? `param6004_0_${item.value}&DSM${
                                          item.label
                                      }灵敏度配置&新配置&${JSON.stringify(
                                          val[`param6004_0_${item.value}`]
                                      )}`
                                    : null;
                        }
                    );
                    this.$emit("setFormChange", this.setForm);
                }
            },
            deep: true,
            immediate: true,
        },
    },
    methods: {
        resetValue() {
            this.$confirm(
                `此操作将${
                    ["低", "中", "高"][this.sentivityType]
                }灵敏度参数配置恢复默认值, 是否继续?`,
                this.$t("common.prompt"),
                {
                    confirmButtonText: this.$t("common.ok"),
                    cancelButtonText: this.$t("common.cancel"),
                    type: "warning",
                }
            )
                .then(() => {
                    this.newForm[`param6004_0_${this.sentivityType}`] =
                        JSON.parse(
                            JSON.stringify(
                                this.newForm[
                                    `param6004_1_${this.sentivityType}`
                                ]
                            )
                        );
                    this.$message({
                        type: "success",
                        message: "恢复默认值成功!",
                    });
                })
                .catch(() => {});
        },
    },
};
</script>
<style lang="less" scoped>
@import "./configurationForm.less";
:deep(.el-collapse){
    .el-collapse-item__content {
        padding-top: 20px;
    }
}
.DSM-Algorithm {
    padding-right: 12px;
    height: 500px;
    .form-title {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 8px 0;
        & > span {
            font-size: 14px;
            font-weight: bold;
            line-height: 27px;
        }
    }
    .collapse-box {
        height: 425px;
        overflow-y: auto;
    }
}
</style>
